server:
  servlet:
    context-path: /ideal-svc
  port: 8083
# MapStruct configuration
mapstruct:
  defaultComponentModel: spring
default:
  password: Jk@1992
spring:
  application:
    name: @artifactId@
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: Nasruddin.nk44@gmail.com
    password: ${mail.password:nswiandgxmkoagcn}
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/idealimport?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&default-storage-engine=myisam&createDatabaseIfNotExist=true}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    hikari:
      pool-name: ideal_import-pool
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 50000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
      hibernate.hbm2ddl.auto: update
    repositories:
      auditing:
        enabled: true
springdoc:
  show-actuator: true
  #use-management-port: true

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
mail:
  login-credential: user_register